// Generated by CoffeeScript 1.6.2
(function() {
  var filter, handler;

  handler = function(details) {
    console.log("*************************** " + (JSON.stringify(details)));
    if (details.parentFrameId === 0) {
      chrome.tabs.create({
        url: details.url,
        active: false
      });
      return {
        cancel: true
      };
    }
  };

  filter = {
    urls: ['*://av.vimeo.com/*.mp4*', '*://*.vimeocdn.com/*.mp4*']
  };

  console.log("*************************** starting up");

  chrome.webRequest.onBeforeRequest.addListener(handler, filter);

}).call(this);
